spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cobodeal
    username: cobouser
    password: password

server:
  port: 8181


mail:
  host: smtp.gmail.com
  port: 587
  username: kumar.gj10@gmail.com
  password: iuyozmdrbnkcuour
  properties.mail.smtp:
    auth: true
    starttls.enable: true

auth:
  secret-key: 7424483cb89294afa20702925d5cb33beb9312f63fdacaa78e8da0a86f89702e
  verify-url: localhost:8181/api/v1/auth/verify-email
  jwt:
    expiration: 86400000 # a day
    refresh-token:
      expiration: 604800000 # 7 days

